name: Publish Package & Storybook

on:
  push:
    branches:
      - main

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Latest
        run: yarn build && yarn build-storybook
        env:
          NODE_OPTIONS: --max-old-space-size=8096

      - name: Publish NPM Package
        run: yarn publish --non-interactive --access public ./package.json
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Update GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
